apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: crossplane
    platform.rezakara.demo/tenant: payment
  name: gitops-payment
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: gitops-payment
  project: default
  source:
    helm:
      values: |
        azure:
          principalType: user
        tenant:
          argocd:
            syncRepos:
            - https://github.com/fluxdojo/platform-deploy-payment
          bindings:
          - cluster: minikube-workload
            entraID:
              appRoleUUID: cf7ba269-9305-5cbd-85e5-e4f802b36025
              assignment:
                principalObjectId: 380a9904-2f8f-4d15-a40c-e2059c88f8ee
            environmentPrefix: wl
            role: admin
          dnsName: pay
          name: payment
          roles:
          - name: admin
            policies:
            - actions:
              - get
              - update
              - delete
              - sync
              - action/apps/Deployment/pause
              - action/apps/Deployment/resume
              - action/apps/Deployment/restart
              - action/batch/CronJob/create-job
              resource: applications
            - actions:
              - get
              resource: logs
    path: charts/gitops-tenant
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: crossplane
    platform.rezakara.demo/prefix: wl
    platform.rezakara.demo/tenant: payment
  name: baseline-payment-wl
  namespace: argocd
spec:
  destination:
    name: minikube-workload
    namespace: payment
  project: default
  source:
    helm:
      values: |
        environmentPrefix: wl
        tenant:
          dnsName: pay
          name: payment
    path: charts/baseline-tenant
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: main
