apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: crossplane
    platform.rezakara.demo/tenant: payment
  name: gitops-payment
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: gitops-payment
  project: default
  source:
    path: charts/gitops-tenant
    repoURL: https://github.com/rezakaramad/kubepave.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: crossplane
    platform.rezakara.demo/prefix: wl
    platform.rezakara.demo/tenant: payment
  name: baseline-payment-wl
  namespace: argocd
spec:
  destination:
    name: minikube-workload
    namespace: payment
  project: default
  source:
    path: charts/baseline-tenant
    repoURL: https://github.com/rezakaramad/kubepave.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
